# Generated by Django 2.1.7 on 2019-03-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('address', models.TextField(max_length=400)),
                ('is_localised', models.BooleanField(default=False)),
                ('date_localised', models.DateTimeField()),
                ('addresse_localised', models.TextField(max_length=400)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geojson_response', models.TextField()),
            ],
        ),
    ]
