# Generated by Django 2.1.7 on 2019-03-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='addresse_localised',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='date_localised',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='geojson_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
