# Generated by Django 2.1.7 on 2019-03-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0005_quotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
