# Generated by Django 2.1.7 on 2019-03-13 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carto', '0007_poicategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poi_set', to='carto.POICategory'),
        ),
    ]
